######################################################################
# Automatically generated by qmake (2.01a) So. Jan 23 21:15:21 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Sender.h Window.h
SOURCES += main.cpp Sender.cpp Window.cpp
