######################################################################
# Automatically generated by qmake (2.01a) Mo. Jan 17 15:02:17 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Sender.h Window.h
SOURCES += main.cpp Sender.cpp Window.cpp
